package:
  name: numbapro
  version: {{ environ['GIT_DESCRIBE_TAG'] }}

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}

source:
  git_url: git@github.com:ContinuumIO/numbapro.git
  git_tag: master

requirements:
  build:
    - python
    - numba >=0.16
    - numpy
  run:
    - python
    - numpy
    - numba >=0.16
    - cudatoolkit
    - numbapro_cudalib

test:
  requires:
    - scipy
    - unittest2       [py26]
  imports:
    - numbapro
    - numbapro.vectorizers.workqueue

about:
  home:
  license: proprietary - Continuum Analytics, Inc.
