package:
  name: numbapro
  version: latest

source:
  git_url: git@github.com:ContinuumIO/numbapro.git
  git_tag: 0.12.7

requirements:
  build:
    - python
    - numba
    - numpy
  run:
    - python
    - numpy
    - numba
    - llvmpy
    - cudatoolkit

test:
  requires:
    - python
    - nose
  imports:
    - numbapro
    - numbapro._utils.mviewbuf

about:
  home:
  license: proprietary - Continuum Analytics, Inc.
